/**************************************************************************
 *
 * Copyright (c) 2014-2017 Jorge Nunes, All Rights Reserved.
 *
 *//**
 *
 * @file avrtk/buttons/ButtonChannel.h
 *
 * @brief Definition of the ButtonChannel class methods.
 *
 **************************************************************************/

#include <stddef.h>

#include <avrtk/buttons/ButtonChannel.h>


/**
 * @class ButtonChannel avrtk/buttons/ButtonChannel.h <avrtk/buttons/ButtonChannel.h>
 * @ingroup avrtk_buttons
 *
 * @brief Represents one concrete button.
 *
 * A button channel is used for notifying listeners of button presses
 * and releases.
 */


/**
 * Initializes a ButtonChannel object.
 *
 * @public @memberof ButtonChannel
 *
 * @param self Reference to the ButtonChannel object to be
 * initialized.
 */
ButtonChannel *ButtonChannel_init(ButtonChannel *self) {

    // TBD
    return NULL;
}


/**
 * Registers a listener to be notified of events related with this
 * button.
 *
 * A given listener instance must only be added to one
 * ButtonChannel. Doing otherwise results in undefined behaviour.
 *
 * @public @memberof ButtonChannel
 *
 * @param self
 *
 * @param listener The listener object that will be notified of events
 * generated by this button.
 */
void ButtonChannel_addButtonListener(
        ButtonChannel *self,
        ButtonListener *listener) {

    // TBD
}


/**
 * Checks if the button is currently in the pressed state.
 *
 * @public @memberof ButtonChannel
 *
 * @param self
 *
 * @return True if the button is currently in the pressed state. False
 * otherwise.
 */
bool ButtonChannel_isPressed(ButtonChannel *self) {

    // TBD
    return false;
}
