/**************************************************************************
 *
 * Copyright (c) 2014 Jorge Nunes, All Rights Reserved.
 *
 *//**
 *
 * @file avrtk/events/Event.h
 *
 * @brief Definition of the Event class methods.
 *
 **************************************************************************/

#include <avrtk/events/Event.h>





/**********************************************************************//**
 *
 * @class Event avrtk/events/Event.h <avrtk/events/Event.h>
 *
 * @brief An event generated by an event source.
 *
 * An event has an associated EventType.
 *
 **************************************************************************/





/**********************************************************************//**
 *
 * Initializes an Event object.
 *
 * @public @memberof Event
 *
 * @param self Reference to the Event object to be initialized.
 *
 * @param eventType The EventType to be associated with this event.
 *
 **************************************************************************/

Event *Event_init(Event     *self,
                  EventType *eventType) {

    self->eventType = eventType;

    return self;
}





/**********************************************************************//**
 *
 * Retrieves the event type for this event.
 *
 * @public @memberof Event
 *
 * @param self 
 *
 * @return The event type for this event, that had been specified in
 * the constructor.
 *
 **************************************************************************/

EventType *Event_getEventType(Event *self) {

    return self->eventType;
}





/**************************************************************************
 *
 * 
 *
 **************************************************************************/

