###########################################################################
#
# Copyright (c) 2014 Jorge Nunes, All Rights Reserved.
#
###########################################################################

B_PROJ_ROOT = ../..

include $(B_PROJ_ROOT)/make/avrtk.make


B_PROJ = BlinkVariable


#
# The main sources, to be compiled with AVR-GCC.
#

B_MAIN_C_SOURCES = \
	BlinkVariable.c


include $(B_PROJ_ROOT)/make/avrtk-demo.make 

